### ISSUE TITLE
Container Registry and Image Name Not Supplied

### ISSUE THREAD

**Issue by eldrly** [Azure-Samples/azure-search-knowledge-mining#102]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In 02 - Web UI Template under 2. Run the UI, the following property is not supplied.: ACR_NAME/IMAGE_NAME.
It is not possible to run the pre-built docker image without the reference to its container registry and name. 

### Any log messages given by the failure
> None

### Expected/desired behavior
> That the correct container registry and name be supplied by Microsoft. 

### OS and Version?
> Windows 11

### Versions
> None

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Thank you for reporting this. We will take a look and update soon!

**Comment by ruoccofabrizio** [comment]
Details added to the doc. Thanks for reporting.
