### ISSUE TITLE
Unable to deploy using the UI Template Deployment (need to approve terms but no place to do so)

### ISSUE THREAD

**Issue by aldelar** [Azure-Samples/azure-search-knowledge-mining#103]
### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Click on 'Deploy to Azure' button
> fill in parameters, click on 'Review + Create'

### Any log messages given by the failure
> You will need to Agree to the terms of service below to create this resource successfully.

### Expected/desired behavior
> Template is validated and offers option to deploy.

### OS and Version?
> N/A

### Versions
> N/A

**Comment by aldelar** [comment]
@gmndrg, @farzad528 : not sure if you've seen this issue I filed 2 weeks ago. But one is unable at this point to deploy this accelerator using the Azure portal. A terms agreement is required but there is no way to accept them from the portal.

**Comment by gmndrg** [comment]
Hello @aldelar we will take a look and provide an update as soon as we can. Thank you for your patience.

**Comment by gmndrg** [comment]
@aldelar I would like to confirm the steps you're following:
Under '00 - Resource Deployment'  you're following the ARM deployment as part of step 2, clicking the button and then at the end, you're getting the following message: 

![image](https://user-images.githubusercontent.com/46359679/181388932-11c74d49-6b18-4fc5-b6c2-52744defad93.png)

Have you clicked on 'Create'? I will try to repro and see which is the resource reporting that, but you should be able to create it and it will approve the terms. It looks like a verification error only that needs to be avoided in the template. If you are still not able to do this, I'll ping you separately. Thanks.

**Comment by aldelar** [comment]
@gmndrg : I did not think of even trying to click Create, as usually when an error like this pops up it blocks the creation process as the resource is considered invalid. But I see now that this is more of a warning or information message and the Create button is actually not grayed out.

I see that Create does goes through and launches the process.

So it's just cosmetic at this point, I thought it was a blocking error.

**Comment by gmndrg** [comment]
Hi @aldelar thank you so much for confirming. The template has not been changed in a few years, what makes me think that the Terms acceptance is something new (for this specific deployment type) and we'll check for the way to set the flag to be able to submit only if checked and so the error is removed and not confusing any longer.

**Comment by aldelar** [comment]
That sounds great @gmndrg. I got tricked into thinking it was a blocking error, I may not be the only one.

**Comment by stevehose** [comment]
Here is what it looks like from PowerShell. The script continues and leaves me with part of the work done and part of it incomplete. Stopping on this error would be far better.
![image](https://user-images.githubusercontent.com/33662177/190411355-420a9c73-9b31-4d4a-8c6d-41850fc68388.png)

**Comment by gmndrg** [comment]
HI @stevehose that is a different issue since the one showing in the portal is not blocking and it would create the deployment if you click create. We will work to have the PowerShell have a section to agree to the Terms of Use. Like I mentioned above, The policy was introduced recently so we need to make sure we understand the steps to have it corrected, Thank you so much for reporting the PowerShell error. This is the first time someone brings this up.

**Comment by gmndrg** [comment]
Hello @stevehose I have submitted a PR for the fix of PowerShell script to stop the execution if Legal Terms are not read and agreed upon and documentation update. This should be published in a few weeks, tops. Thanks again for reporting this!

**Comment by stevehose** [comment]
@gmndrg - that is outstanding! I have been trying to find a way to accept terms from code and haven't had any luck! :)

**Comment by gmndrg** [comment]
We cannot remove the Terms of use since automatic from Cognitive Services resource, but since this is deployed, we'll proceed to mark this as resolved, since not blocking for the deployment.

**Comment by stevehose** [comment]
I agree. The terms should be reviewed and accepted. I also appreciate the PR. I went ahead and leveraged the new code in my project before it was merged. Thanks again!! It's perfect!
