### ISSUE TITLE
Struggling with Docker and Step 2

### ISSUE THREAD

**Issue by cott8161** [Azure-Samples/azure-search-knowledge-mining#112]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

I struggled to connect Docker with the resources that I provisioned. On the "02 - Web UI Template", I was unable to run this command:

"docker run -d --env-file .env -p 80:80 kmworkshop.azurecr.io/web-ui:latest"

I tried to use the visual studio path instead of using the Docker path, however, the instructions on the Visual Studio path weren't clear either. It didn't provide any instructions on how to ensure that your Web Services app was connected to the resources provisioned earlier. Maybe I'm misunderstanding the instructions there, but I'd love more clarity around that.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
We will work to provide more clarity about the instructions. Thank you for the feedback!

**Comment by lenisha** [comment]
we had similar confusion on web app part and added screenshots in #115
