### ISSUE TITLE
autocomplete does not popup

### ISSUE THREAD

**Issue by lenisha** [Azure-Samples/azure-search-knowledge-mining#16]
JS scripts for autocomplete is not invoked , is there additional setup needed?

 $(function () {
            $('.advancedAutoComplete').autocomplete({
                source: "/home/suggest",
                minLength: 2,
                select: function (event, ui) {
                    Search();
                }
            });
        })

@LuisCabrer ?

**Comment by LuisCabrer** [comment]
Yes, you need to set a suggester in your index. Did you set one?

Other than that, you need to type something that is at least to characters long and wait a bit to see the results in the autocomplete.

**Comment by dereklegenzoff** [comment]
Closing this issue as there hasn't been any activity for a while.
