### ISSUE TITLE
Postman collection Environment variables is not correct

### ISSUE THREAD

**Issue by johndeu** [Azure-Samples/azure-search-knowledge-mining#29]
Looks like someone may have overwritten the Postman Environment variables file with the actual collection. So you are unable to import the env. settings file currently.  Please fix.

**Comment by marktab** [comment]
Agreed

Should be something like the older file

![image](https://user-images.githubusercontent.com/12258589/68210271-2d85b400-ffa3-11e9-9818-13a6f8c0025c.png)
tagging @delegenz

**Comment by dereklegenzoff** [comment]
@johndeu  and @marktab, the latest PR has been merged so this issue is now resolved. Please close this issue.

**Comment by marktab** [comment]
Thanks @dereklegenzoff  -- I cannot close it, but @johndeu maybe can
