### ISSUE TITLE
Knowledge Mining Workshop: metadata_storage_path is Base64 encoded twice

### ISSUE THREAD

**Issue by pmeirelesf** [Azure-Samples/azure-search-knowledge-mining#33]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Complete Module 0 and Module 1;
2. Open your index's Search explorer and query for * (or anything else);
3. Look the Results panel, this is a extract of my first result:
"metadata_storage_name": "NCT00943111.pdf",
"metadata_storage_path": "YQBIAFIAMABjAEgATQA2AEwAeQA5AHMAWgAzAEIAdABaAG0AdAB0AGQAMwBOADAAYgAzAEoAaABaADIAVQB1AFkAbQB4AHYAWQBpADUAagBiADMASgBsAEwAbgBkAHAAYgBtAFIAdgBkADMATQB1AGIAbQBWADAATAAyAE4AcwBhAFcANQBwAFkAMgBGAHMATABYAFIAeQBhAFcARgBzAGMAeQAxAHoAYgBXAEYAcwBiAEMAOQBPAFEAMQBRAHcATQBEAGsAMABNAHoARQB4AE0AUwA1AHcAWgBHAFkAMQA1"
4. Take the metadata_storage_path value and use some tool to decode Base64 (like https://www.base64decode.org), then you should get:
aHR0cHM6Ly9sZ3BtZmttd3N0b3JhZ2UuYmxvYi5jb3JlLndpbmRvd3MubmV0L2NsaW5pY2FsLXRyaWFscy1zbWFsbC9OQ1QwMDk0MzExMS5wZGY15
5. As it is still encoded, decode this value once more. The result will be correct now:
https://lgpmfkmwstorage.blob.core.windows.net/clinical-trials-small/NCT00943111.pdf5

Because metadata_storage_path is encoded twice, details.js is unable to preview any file (line 24 will fail to decode the path).

I suspect it has something to do with the way the Index is created, because I have no problem to preview files with Knowledge Mining Solution Accelerator deployment.

### Any log messages given by the failure
This file cannot be previewed. Download it here to view: Download

### Expected/desired behavior
The Index field metadata_storage_path be encoded only once.

### OS and Version?
Windows 10.

### Versions
Latest.

**Comment by iMicknl** [comment]
@LuisCabrer could this be a service issue? I just came across a [related issue on StackOverflow](https://stackoverflow.com/questions/58918171/metadata-storage-path-encoded-2-times-from-azure-blob-storage).

**Comment by LuisCabrer** [comment]
This is really strange, and not what I see on my side. @cynotebo would you have a few cycles to look into this one?

**Comment by iMicknl** [comment]
@LuisCabrer looks like this has already been resolved, apparently it was only an issue when the indexer has been created from the UI.


>Yes, this is a bug in the UI and we have a fix that should be deployed no later than 2019 Nov 14:00 PDT.
>Unfortunately you'll need to recreate your Index and Indexer if the double-encoding is a problem. You can wait until the UI update is out and use it to recreate, or you can use a tool such as Postman to manually recreate the Indexer, using the REST documentation as a guide.
([source](https://stackoverflow.com/a/58925323/3554973))

**Comment by pmeirelesf** [comment]
I confirm this problem was fixed, I've just created a new index and now the metadata_storage_path is encoded only once (as expected). Thank you all for your support!

**Comment by LuisCabrer** [comment]
Perfect, thanks!

**Comment by htwashere** [comment]
Hi there, thanks for this fix, I was able to decode the storage path. I'm not sure if it is appropriate for me to raise an issue I encountered here, but thought I would try to see if you have an easy answer: when decoding to Ascii using javascript (I tried mainly using atob method and other utilities I could find googling), I get some garbled characters which I could not find a handy solution to it. For example, even with your test case above (YQBIAFIAMABjAEgATQA2AEwAeQA...), if you decode it, you will get something like "a�H�R�0�c�H�M�6...".  I tried various chars conversion, adding a <meta charset="UTF-8"> in the <head> section to no avail.

...thanks.

**Comment by KirubelTolosa** [comment]
@LuisCabrer 
I just wanted to mention that I run into the same problem of the file not being previewed, although the fix might have already been deployed. The URI section of the path was double encoded. I had to decode the decoded-path attribute for the blob to be previewed. 
`var path = Base64Decode(data.decodedPath) + data.token; // direct path to blob with auth token`
Same with the metadata_storage_path. This fixed it. Recreating the index didn't help.  I hope this helps someone in the future.

**Comment by KirubelTolosa** [comment]
> Hi there, thanks for this fix, I was able to decode the storage path. I'm not sure if it is appropriate for me to raise an issue I encountered here, but thought I would try to see if you have an easy answer: when decoding to Ascii using javascript (I tried mainly using atob method and other utilities I could find googling), I get some garbled characters which I could not find a handy solution to it. For example, even with your test case above (YQBIAFIAMABjAEgATQA2AEwAeQA...), if you decode it, you will get something like "a�H�R�0�c�H�M�6...". I tried various chars conversion, adding a in the section to no avail.
> 
> ...thanks.

The Base64Decode() method should do it. Make sure you pass the URI string without the token. Hope this helps.

**Comment by LuisCabrer** [comment]
> @LuisCabrer
> I just wanted to mention that I run into the same problem of the file not being previewed, although the fix might have already been deployed. The URI section of the path was double encoded. I had to decode the decoded-path attribute for the blob to be previewed.
> `var path = Base64Decode(data.decodedPath) + data.token; // direct path to blob with auth token`
> Same with the metadata_storage_path. This fixed it. Recreating the index didn't help. I hope this helps someone in the future.

@KirubelTolosa , are you saying that the issue still exists???

**Comment by KirubelTolosa** [comment]
Yes. In some form. The "decoded path" needed one more time of decoding. 
This may entirely be unrelated but it only happened after I implemented Azure app configuration and Key Vault as configuration providers for the UI. I was not having this issue before.
