### ISSUE TITLE
Document not opening while clicking in it

### ISSUE THREAD

**Issue by rajat28negi** [Azure-Samples/azure-search-knowledge-mining#34]
**While I am clicking in any doc i m getting this error:**
![Problem3](https://user-images.githubusercontent.com/37389757/69314472-41474080-0c5a-11ea-808e-fa9e74039ccf.JPG)
 and the error is: **"Cannot read property 'metadata_storage_path' of null"**

**Comment by dereklegenzoff** [comment]
Hey @rajat28negi, could you confirm that metadata_storage_path exists in your search index?

**Comment by MercyPrasanna** [comment]
I also face the same issue. Is this resolved? metadata_storage_path does exist in the index and has values, I see the issue with the token, which is null.

**Comment by dereklegenzoff** [comment]
Hi there - sorry for the very slow reply. This issue is likely caused by the container name not being specified correctly. We've added some additional error messages in the UI that should help make debugging easier.

Please re-open this issue if you face additional challenges.
