### ISSUE TITLE
Azure search inbuilt cognitive skill extracting the wrong entity-location name.

### ISSUE THREAD

**Issue by rajat28negi** [Azure-Samples/azure-search-knowledge-mining#36]
![problemLocation](https://user-images.githubusercontent.com/37389757/70217598-7a59d780-1767-11ea-8dbd-9c7ae504e021.JPG)

Some location are not right. And same things happening with other enitity extraction as well

**Comment by dereklegenzoff** [comment]
Hi @rajat28negi - apologies for the very slow reply. Azure Cognitive Search uses the [text analytics cognitive services](https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics) to extract entities. We're currently working to provide support for V3 of the text analytics cognitive services which should improve the entity extraction results.

Please reopen this issue if you face additional challenges.
