### ISSUE TITLE
Getting an error while opening Web UI Template

### ISSUE THREAD

**Issue by RahulSinghYYC** [Azure-Samples/azure-search-knowledge-mining#37]
When i try to excecute the Web UR Template from visual studio 2019 i receive an error . 
An unhandled exception occurred while processing the request.
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.IHttpResponseStreamWriterFactory' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by dereklegenzoff** [comment]
Hi @RahulSinghYYC - apologies for the very slow reply. There have been additional updates made to make it easier to debug issues in the UI. Please re-open this issue if you have more problems.
