### ISSUE TITLE
link of Postman documentation needs update

### ISSUE THREAD

**Issue by stephenhallfr-zz** [Azure-Samples/azure-search-knowledge-mining#42]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>on the https://github.com/Azure-Samples/azure-search-knowledge-mining/tree/master/01%20-%20Search%20Index%20Creation the link to postman documentation needs to be updated.

the link is https://learning.postman.com/docs/postman/launching-postman/introduction/

### Any log messages given by the failure
>

### Expected/desired behavior
> link should work

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Thanks for pointing this out. I agree the link you provided is a better link. I've updated the link so I will close the issue for now.
