### ISSUE TITLE
Workshops Module 1 and 2

### ISSUE THREAD

**Issue by PekkaGH** [Azure-Samples/azure-search-knowledge-mining#43]
I didn't have Locations-field at all in the index definition. I had Organizations-field. Well guessed they are probably the same. But then in Module 2 the VS solution didn't work, it opened the web page but didn't bring any results.

**Comment by dereklegenzoff** [comment]
Hey @PekkaGH, there's a few different things that could cause this. Does your index have a metadata_title field? If not, we merged a PR yesterday that fixed a bug: https://github.com/Azure-Samples/azure-search-knowledge-mining/pull/41/files.

Another good way to debug is to put a breakpoint on line 69 of DocumentSearchClient.cs and step through from there to see if an exception is being caught somewhere

**Comment by PekkaGH** [comment]
Yeah, Now it's working. Thanks!
