### ISSUE TITLE
Any roadmap of Web UI for nodejs or another language? 

### ISSUE THREAD

**Issue by vrlb** [Azure-Samples/azure-search-knowledge-mining#45]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Any roadmap of Web UI for nodejs or another language?

**Comment by dereklegenzoff** [comment]
Hi @vrlb - sorry for the very slow reply. We now have a react template that's written entirelyy in Javascript that is available here: https://github.com/dereklegenzoff/azure-search-react-template

Feel free to re-open this issue if you have any additional questions.
