### ISSUE TITLE
Text refers to a skills section that has been moved

### ISSUE THREAD

**Issue by ignaciofls** [Azure-Samples/azure-search-knowledge-mining#55]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
The link https://github.com/Azure-Samples/azure-search-knowledge-mining/tree/master/02%20-%20Web%20UI%20Template refers to a skill subfolder that has moved to https://github.com/Azure-Samples/azure-search-knowledge-mining/tree/master/03 - Data Science and Custom Skills/Azure Function Custom Skills . Please remove the text saying: "The Cognitive Search Template contains two projects"... for more clarity 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Done, thanks for flagging this, Ignacio! Apologies for the slow reply.
