### ISSUE TITLE
Multiple Index and Storages with different buttons at home page. 

### ISSUE THREAD

**Issue by jorgegarcia197** [Azure-Samples/azure-search-knowledge-mining#56]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The steps are the same as the Workshop 1 and 2 

### Expected/desired behavior
> Hi, firstly I would like to thank you because of how great this project is. I have been using it for a while now and now I am trying to work on a future step on my own, but I am not familiarized that well with the code structure of the repository. What I would like to do is to have four different buttons on the home page (that I know how to do in the Home HTML) but what I would like to ask is how can I link that button to one storage and just display the files within that Blob Storage and the other buttons to the next storages. I think it has to do something with the storage Controller, but I am not sure. 

Thanks in advance 

### OS and Version?
> Windows 10.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi @jorgegarcia197 - apologies for the slow reply. This is certainly possible but would take a bit of time to implement. The first step would probably be to add multiple `DocumentSearchClient`s to the [HomeController](https://github.com/Azure-Samples/azure-search-knowledge-mining/blob/master/02%20-%20Web%20UI%20Template/CognitiveSearch.UI/Controllers/HomeController.cs). From there you could add some additional logic to route the query to the correct `DocumentSearchClient`. To do that, you'd need to update some of the files under [wwwroot/js](https://github.com/Azure-Samples/azure-search-knowledge-mining/tree/master/02%20-%20Web%20UI%20Template/CognitiveSearch.UI/wwwroot/js).

**Comment by jorgegarcia197** [comment]
Thank you! will look into that in detail and come back too you if further questions arise.

**Comment by dereklegenzoff** [comment]
Closing this issue for now. @jorgegarcia197 - please feel free to reopen the issue if you have additionall questions.
