### ISSUE TITLE
Many of the links on the Readme (under workshop) appear to be broken

### ISSUE THREAD

**Issue by KBaroni** [Azure-Samples/azure-search-knowledge-mining#61]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)
```
Most of the workshop links are broken and will render a 'not found'.  The readme has this link:  https://github.com/Azure-Samples/azure-search-knowledge-mining/workshops/Module%200.md but the correct link appears to be:  https://github.com/Azure-Samples/azure-search-knowledge-mining/blob/master/workshops/Module%200.md
### Minimal steps to reproduce
>
The workshop link for Module 7 works but others do not.   Displays a 'not found'. 
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Thanks for flagging this. I made the links hard-coded so they would work on this [page](https://docs.microsoft.com/en-us/samples/azure-samples/azure-search-knowledge-mining/azure-search-knowledge-mining/) but it looks like I broke them in the process.

I merged a PR to fix this issues so I'm going ahead and closing it. Please re-open the issue if you find any additional broken links.
