### ISSUE TITLE
Pre-reqs blob not copying metadata

### ISSUE THREAD

**Issue by Chrisd77** [Azure-Samples/azure-search-knowledge-mining#63]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting

Hi
I'm getting the following error when trying to copy the blob container data to my blob storage area. Any ideas what might be causing this? When I get to stage 2 and completed the UI build using Visual studio the autosuggest works but it doesn't return any search results on the page. I'm assuming this second bug is caused by no metadata being migrated.

"The properties and metadata for this container cannot be determined and will not be copied to the new container. Proceed with the copy?"

```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi @Chrisd77 -- so sorry I never responded to this. It somehow fell through the cracks. I'm assuming it's too late but we've since updated this SAS URI and things should be working for you now. I'm going to close this issue for now but please do feel free to reopen it if you have any further questions.
