### ISSUE TITLE
SAS token has expired for clinical-trials-small

### ISSUE THREAD

**Issue by amandajeanhoward11** [Azure-Samples/azure-search-knowledge-mining#67]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Copy the storage container that holds clinical trials from a read only location to your Storage Account.

1) Open Azure Storage Explorer and select Managed Accounts, Add and Account..., Use a shared access signature (SAS) URI. The Display name will autofill. Select Next
2) Add the following URI, then select Next, then select Connect

At this step the URI provided gives a SAS token has expired error

### Any log messages given by the failure
>
The SAS token has expired.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
windows 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi @amandajeanhoward11 - thanks for flagging this issue. I've gone ahead and generated a new SAS token and updated the file. 

I've included the token below for your convenience:
```
https://kmworkshop.blob.core.windows.net/clinical-trials-small?sv=2019-10-10&st=2020-09-14T19%3A21%3A00Z&se=2022-09-16T19%3A21%3A00Z&sr=c&sp=rl&sig=CtoGmOSkbap8ZOslI9EYeWs148gw4NdYpynU0Eyoj4s%3D
```
