### ISSUE TITLE
Module 4 instructions in the workshop extremely confusing

### ISSUE THREAD

**Issue by toomuchvoltage** [Azure-Samples/azure-search-knowledge-mining#71]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The section titled "Add a new record to the Shaper Skill, and add a new Table Projection" is extremely confusing. When I even try to add 'new diseases input into the Shaper Skill' with what I can gather I get the error pasted below:

### Any log messages given by the failure
> {
    "error": {
        "code": "",
        "message": "Enricher definitions create a cyclic dependency"
    }
}

### Expected/desired behavior
> The instructions should clearly describe the steps to add new disease inputs and new table projections.

### OS and Version?
> All OSes/versions

### Versions
>Current version

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by toomuchvoltage** [comment]
Hi there... I managed to figure out what was requested. Some additional instructions up front on how to find ShaperSkill would add a lot of clarity to the module.

Also the my_phonetic analyzer in Module 5 seems to be not supported with either api version **2019-05-06-Preview** or **2019-05-06**. I keep getting the following error in the response body:
```
{
    "error": {
        "code": "",
        "message": "The request is invalid. Details: definition : The field 'diseasesPhonetic' uses an analyzer 'my_phonetic' which is unknown or not supported in the API version used in the request.\r\n"
    }
}
```

**Comment by dereklegenzoff** [comment]
Hi @toomuchvoltage - I'm sorry to hear you found the module confusing and I appreciate the feedback on how we can improve it. I'll look into seeing if we can make that section more clear. 

Regarding the phonetic analyzer, could you confirm you've declared the `my_phonetic` analyzer in the index definition? The index definition should look something like this:

```json
{
    "name": "my-index",
    "fields": [
        ...,
        {
            "name": "diseasesPhonetic",
            "type": "Collection(Edm.String)",
            "searchable": true,
            "filterable": true,
            "retrievable": true,
            "sortable": false,
            "facetable": true,
            "key": false,
            "indexAnalyzer": null,
            "searchAnalyzer": null,
            "analyzer": "my_phonetic",
            "synonymMaps": []
        }...
    ],
    "analyzers": [
        {
            "name": "my_phonetic",
            "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
            "tokenizer": "microsoft_language_tokenizer",
            "tokenFilters": [
                "lowercase",
                "asciifolding",
                "phonetic_token_filter"
            ]
        }
    ],
    "tokenFilters": [
        {
            "name": "phonetic_token_filter",
            "@odata.type": "#Microsoft.Azure.Search.PhoneticTokenFilter",
            "encoder": "doubleMetaphone"
        }
    ],
}
```

If you already have that declared, could you share your index definition with me so I could help debug?

**Comment by toomuchvoltage** [comment]
Ahh yes, this was the issue. I think it has again come down to just a tad bit of clarity in the instructions. If the instructions appear before the explanations it might help greatly.
