### ISSUE TITLE
Bootcamp link dead

### ISSUE THREAD

**Issue by recklessop** [Azure-Samples/azure-search-knowledge-mining#82]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Read the README.md file, and look for the Bootcamp link.

### Any log messages given by the failure
>
404 error

### Expected/desired behavior
>
A working Link

**Comment by dereklegenzoff** [comment]
Sorry about that. Here is the updated link: [https://github.com/MicrosoftLearning/LearnAI-KnowledgeMiningBootcamp](https://github.com/MicrosoftLearning/LearnAI-KnowledgeMiningBootcamp).

I will get the readme updated.
