### ISSUE TITLE
02 - Web UI Template does not return back search results

### ISSUE THREAD

**Issue by ujvalgandhi1** [Azure-Samples/azure-search-knowledge-mining#85]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I cloned the Github repo to a local folder and followed the instructions to deploy the solution via the Portal to my subscription. I tried the Search Explorer and the query returns back search results. Then I set up the appsettings.json outlined in the 02 - Web UI Template and compiled it. The search results do not get displayed now but the entity map returns back the network diagram visual. 

### Any log messages given by the failure
> The console returns an error "entityMap.js:47 Uncaught TypeError: Cannot read property 'style' of null"

### Expected/desired behavior
> Search Results are returned

### OS and Version?
> Windows 10, Azure Commercial Subscription

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Closing this as the issue was resolved offline. In this case, the index had a field named metadata_title that wasn't marked as retrievable that caused the issue.

Putting a breakpoint in the `Search()` method of  **DocumentSearchClient.cs** is a great way to debug issues like this.
