### ISSUE TITLE
Module 2 System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by tgokal** [Azure-Samples/azure-search-knowledge-mining#87]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run CognitiveSearch.UI at end of Module 2. Type phrase in search bar when web app is launched. Exception is thrown in Visual Studio, search is not completed in browser. No other files change except for appsettings.json. 

### Any log messages given by the failure
> Exception thrown: 'System.NullReferenceException' in CognitiveSearch.UI.dll
Object reference not set to an instance of an object.

### Expected/desired behavior
> Search in browser completed, search results appear. 

### OS and Version?
> Windows 10

### Versions
> 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi @tgokal - thanks for filing this issue. There are some fields in the appsettings.json file that can't be removed. Have you removed any of the other fields by chance?

One great way to debug is to put a break in the constructor and `Search()` method of **DocumentSearchClient.cs** to catch any exceptions being thrown (lines 87 and 122 respectively). This can give you a better error message

You can also right click in the web browser -> select inspect -> and then see if there's any errors in the console.

Could you try these things out and share the error message?
