### ISSUE TITLE
Module 3: Unable to test Azure Function locally, 'Output type of Class library cannot be started directly' error. 

### ISSUE THREAD

**Issue by tgokal** [Azure-Samples/azure-search-knowledge-mining#88]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Make CustomEntityLookup as Startup Project and run locally. 

### Any log messages given by the failure
> With the current code and Output Type of Class Library, error thrown is "A project with an Output Type of Class Library cannot be started directly. In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project". 

### Expected/desired behavior
> Azure Function to run and be tested locally. 

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful
I tried changing the output type from Class Library to Console/Windows application, but received the error: 'Program does not contain a static 'Main' method suitable for an entry point. I added a static Main at the end of the CustomEntityLookup class in CustomEntityLookup.cs, but Azure Function did not run and could not be tested. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi @tgokal it sounds like the wrong project may be selected as the startup project. You can choose the name of the project which you want to set default startup project then click to the project on toolbar and then click **Set as startup project**. 

That said, I believe there may be an existing bug with that skill. I'd recommend that you use the new built in equivalent of that skill: [Custom Entity Lookup Skill](https://docs.microsoft.com/en-us/azure/search/cognitive-search-skill-custom-entity-lookup).

I'll try to find some time to update the workshop to point to the built in skill.

**Comment by dereklegenzoff** [comment]
Confirmed that custom entity lookup powerskill is still working so closing this issue.
