### ISSUE TITLE
Clinical Trials Example SAS URI not working

### ISSUE THREAD

**Issue by timomta** [Azure-Samples/azure-search-knowledge-mining#93]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Attempt to access the URL in module 0 of the course, step 4, copy the example files from:
https://kmworkshop.blob.core.windows.net/clinical-trials-small?sv=2019-10-10&st=2020-09-14T19%3A21%3A00Z&se=2022-09-16T19%3A21%3A00Z&sr=c&sp=rl&sig=CtoGmOSkbap8ZOslI9EYeWs148gw4NdYpynU0Eyoj4s%3D

The URL does not work in Storage Explorer when you attempt to add it, and it does not work in a browser, failing with an authentication failure.

### Any log messages given by the failure
> In the browser you will receive the following error:
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:688c96da-401e-0048-7534-5ed8ae000000 Time:2021-06-10T20:10:28.8938011Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was rl 2020-09-14T19:21:00Z 2022-09-16T19:21:00Z /blob/kmworkshop/$root 2019-10-10 c </AuthenticationErrorDetail>
</Error>

### Expected/desired behavior
> Expect to access the sample files so they can be copied to the student storage account

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
Hi @timomta - The SAS token appears to work for me. When adding it to Azure Storage Explorer as described in Module 0, make sure to select *blob container* rather than *storage account* as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/19762985/121603225-48c96880-c9fd-11eb-93a3-6234476f8e80.png)

**Comment by timomta** [comment]
It would be really helpful if this was stated in step 4i, otherwise there are a couple different ways to connect using a SAS URI...

**Comment by dereklegenzoff** [comment]
Thanks @timomta - I think that's fair feedback. We're planning to make some updates to the workshop so I will make sure this gets included as part of that effort.
